name: wassword
description: Wassword - Wonderful Password Generator

version: 3.0.0+25

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flex_seed_scheme: ^3.0.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_styled_toast: ^2.2.1
  go_router: ^14.2.0
  package_info_plus: ^8.0.0
  riverpod_annotation: ^2.3.5
  share_plus: ^9.0.0
  universal_platform: ^1.1.0
  url_launcher: ^6.3.0
  window_manager: ^0.3.9

dev_dependencies:
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icona/
